"""SymPy 推导与 refer/papers 公式审计工具。

本包把报告中的结构公式拆成两层：

* :mod:`myqcd.derivations` 包含可在明确假设下由 SymPy 检查的解析推导；
* :mod:`myqcd.latex_inventory` 对 50 篇中文论文源文件中的显示公式逐条建档。

公式索引中的 ``unparsed`` 只表示尚未在不引入额外物理约定的情况下自动
语义化，并不表示论文公式错误。
"""

from .derivations import (
    DerivationResult,
    derive_collins_soper_evolution,
    derive_correlator_spectrum,
    derive_diffusion_processes,
    derive_gauge_flow_kernel,
    derive_generating_functional,
    derive_gradient_flow,
    derive_gradient_flow_energy_density,
    derive_heat_kernel_semigroup,
    derive_gradient_flow_pole_cancellation,
    derive_hmc_scalar,
    derive_langevin_fokker_planck,
    derive_boosted_smearing_width,
    derive_lattice_dispersion_relations,
    derive_lamet_matching,
    derive_lattice_link,
    derive_mcmc_autocorrelation,
    derive_stout_smearing_su2,
    derive_momentum_smearing_shift,
    derive_mellin_convolution,
    derive_normalizing_flow,
    derive_pseudo_itd,
    derive_pdf_moment_relations,
    derive_phi4_lattice_observables,
    derive_renormalization,
    derive_tmd_fourier,
    derive_quasi_pdf_tmd_relation,
    derive_target_mass_corrections,
    derive_trivializing_map,
    derive_qpdf_ppdf_fourier_inversion,
    derive_flow_mcmc_balance,
    derive_flowed_propagators,
    derive_pseudo_pdf_ir_regulators,
    derive_pseudo_pdf_one_loop,
    derive_quark_gaussian_smearing,
    derive_u1_gauge_invariance,
    derive_u1_lattice_field_strength,
    derive_u1_topological_charge,
    derive_u1_compact_action,
    derive_su3_generator_identities,
    derive_su3_cayley_hamilton,
    derive_correlated_chi_square_profile,
    derive_ising_mean_field,
    derive_ape_projection_su2,
    derive_wilson_eigenvalue_statistics,
    derive_wilson_fourier_endpoint,
    derive_wilson_continuum_scale,
    derive_two_dimensional_wilson_loop,
    derive_wilson_smearing_kernel,
    derive_wilson_smearing_scaling,
    derive_wilson_area_law,
    run_core_checks,
)
from .formula_registry import CORE_FORMULAS, FormulaSpec
from .latex_inventory import (
    FormulaRecord,
    InventoryReport,
    extract_display_formulas,
    scan_refer_papers,
)

__all__ = [
    "CORE_FORMULAS",
    "DerivationResult",
    "FormulaRecord",
    "FormulaSpec",
    "InventoryReport",
    "derive_correlator_spectrum",
    "derive_diffusion_processes",
    "derive_gauge_flow_kernel",
    "derive_collins_soper_evolution",
    "derive_generating_functional",
    "derive_gradient_flow",
    "derive_gradient_flow_energy_density",
    "derive_heat_kernel_semigroup",
    "derive_gradient_flow_pole_cancellation",
    "derive_hmc_scalar",
    "derive_langevin_fokker_planck",
    "derive_boosted_smearing_width",
    "derive_lattice_dispersion_relations",
    "derive_lamet_matching",
    "derive_lattice_link",
    "derive_mcmc_autocorrelation",
    "derive_stout_smearing_su2",
    "derive_momentum_smearing_shift",
    "derive_mellin_convolution",
    "derive_normalizing_flow",
    "derive_pseudo_itd",
    "derive_pdf_moment_relations",
    "derive_phi4_lattice_observables",
    "derive_renormalization",
    "derive_tmd_fourier",
    "derive_quasi_pdf_tmd_relation",
    "derive_target_mass_corrections",
    "derive_trivializing_map",
    "derive_qpdf_ppdf_fourier_inversion",
    "derive_flow_mcmc_balance",
    "derive_flowed_propagators",
    "derive_pseudo_pdf_ir_regulators",
    "derive_pseudo_pdf_one_loop",
    "derive_quark_gaussian_smearing",
    "derive_u1_gauge_invariance",
    "derive_u1_lattice_field_strength",
    "derive_u1_topological_charge",
    "derive_u1_compact_action",
    "derive_su3_generator_identities",
    "derive_su3_cayley_hamilton",
    "derive_correlated_chi_square_profile",
    "derive_ising_mean_field",
    "derive_ape_projection_su2",
    "derive_wilson_eigenvalue_statistics",
    "derive_wilson_fourier_endpoint",
    "derive_wilson_continuum_scale",
    "derive_two_dimensional_wilson_loop",
    "derive_wilson_smearing_kernel",
    "derive_wilson_smearing_scaling",
    "derive_wilson_area_law",
    "extract_display_formulas",
    "run_core_checks",
    "scan_refer_papers",
]
