"""报告公式注册表及其证据边界。"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


@dataclass(frozen=True)
class FormulaSpec:
    """一个结构公式的来源、状态和对应推导入口。"""

    formula_id: str
    latex: str
    source: str
    status: str
    derivation: str
    notes: str


_REPORT = "docs/report_refer_papers_all_contents_20260830.tex"


CORE_FORMULAS: Dict[str, FormulaSpec] = {
    "generating_functional": FormulaSpec(
        "generating_functional",
        r"Z[J]=\int\mathcal D\phi\,\exp[-S_E[\phi]+J\phi]",
        f"{_REPORT}:67-74",
        "structural",
        "derive_generating_functional",
        "SymPy 精确验证有限维高斯自由场类比及源导数关系；一般相互作用泛函不作形式积分假设。",
    ),
    "lattice_link": FormulaSpec(
        "lattice_link",
        r"U_\mu(x)=\exp[iagA_\mu(x+a\hat\mu/2)]",
        f"{_REPORT}:67-74",
        "verified",
        "derive_lattice_link",
        "在可交换单色分量中验证幺正性与 a^2 连续展开；非阿贝尔情形保留矩阵指数解释。",
    ),
    "stout_smearing_su2": FormulaSpec(
        "stout_smearing_su2",
        r"Q=\frac{i}{2}(\Omega^\dagger-\Omega)-\frac{i}{2N}\mathrm{Tr}(\Omega^\dagger-\Omega),\quad U'=e^{iQ}U",
        "refer/papers/Analytic_Smearing_of_SU3_Link_Variables_latex/chapters/section02.tex:21-48,65-100",
        "verified",
        "derive_stout_smearing_su2",
        "用显式 SU(2) Pauli 子群验证 Q 的 Hermitian/无迹性质、stout 更新的 SU(2) 群闭合和共轭协变性。",
    ),
    "quark_gaussian_smearing": FormulaSpec(
        "quark_gaussian_smearing",
        r"J_{\sigma,n_\sigma}=\left(1+\frac{\sigma\nabla^2}{n_\sigma}\right)^{n_\sigma}\to e^{\sigma\nabla^2},\quad \Box=VV^\dagger,\ \Box^2=\Box",
        "refer/papers/夸克场产生算符构造_latex/chapters/section02.tex:25-73",
        "verified",
        "derive_quark_gaussian_smearing",
        "在自由 U_j=1 的 2^3 周期标量格点模型中验证协变 Laplacian 的 Hermitian 结构、平面波本征因子、Jacobi 到 Gaussian 极限，以及正交低秩 Box 投影；一般非阿贝尔协变性和截断误差未由此推出。",
    ),
    "u1_gauge_invariance": FormulaSpec(
        "u1_gauge_invariance",
        r"U_\mu(x)\to\Omega(x)U_\mu(x)\Omega^\dagger(x+\hat\mu),\quad P=U_0U_1U_0^\dagger U_1^\dagger,\quad S=-\beta\,\mathrm{Re}\,P",
        "refer/papers/规范等变的流采样_latex/chapters/section03.tex:1-18; chapters/section05.tex:1-12",
        "verified",
        "derive_u1_gauge_invariance",
        "在有限 2×2 周期 plaquette 的 U(1) 相位表示中逐项验证链变量变换、plaquette、Wilson 作用量及未归一化 Boltzmann 密度不变；不替代一般 SU(3) Haar 测度与动力学证明。",
    ),
    "u1_topological_charge": FormulaSpec(
        "u1_topological_charge",
        r"Q=\frac{1}{2\pi}\sum_x\arg P(x),\quad \chi_Q=\langle Q^2/V\rangle,\quad W_{\ell\times\ell}=\prod_{x\in\ell\times\ell}P(x)",
        "refer/papers/规范等变的流采样_latex/chapters/section05.tex:19-27",
        "verified",
        "derive_u1_topological_charge",
        "在 2×2 周期格点的总磁通 2π 常 plaquette 构型中验证主值相位、Q=1、单构型 Q^2/V=1/4 和 Wilson 圈周期闭合；不替代系综平均、误差或连续极限测量。",
    ),
    "u1_compact_action": FormulaSpec(
        "u1_compact_action",
        r"\frac{1}{2g^2}\left[1-\frac{e^{if}+e^{-if}}{2}\right]=\frac{1-\cos f}{2g^2}=\frac{f^2}{4g^2}+\mathcal O(f^4)",
        "refer/papers/夸克禁闭_latex/chapters/section03.tex:86-108; chapters/section05.tex:16-24",
        "verified",
        "derive_u1_compact_action",
        "在单个实 plaquette 相位的有限维模型中验证指数到余弦的改写、2π 周期性、f→0 二次系数和四阶 Taylor 项；不处理格点约束积分。",
    ),
    "u1_lattice_field_strength": FormulaSpec(
        "u1_lattice_field_strength",
        r"F_{\mu\nu}(n)=\frac{\theta_{\mu\nu}(n)-\theta_{\nu\mu}(n)-\theta_{\mu\nu}(n+\hat\nu)+\theta_{\nu\mu}(n+\hat\mu)}{a},\quad f_{\mu\nu}(n)=aF_{\mu\nu}(n)",
        "refer/papers/夸克禁闭_latex/chapters/section03.tex:63-77",
        "verified",
        "derive_u1_lattice_field_strength",
        "以四个相邻链接角变量显式展开离散 curl，验证局部 U(1) 规范平移的参数完全抵消，并检查 f_{mu nu}=a F_{mu nu}；不展开费米子积分或连续动力学。",
    ),
    "su3_generator_identities": FormulaSpec(
        "su3_generator_identities",
        r"\mathrm{tr}(T^aT^b)=-\frac12\delta^{ab},\quad [T^a,T^b]=f^{abc}T^c,\quad \{T^a,T^b\}=-\frac13\delta^{ab}+id^{abc}T^c,\quad T^a_{\alpha\beta}T^a_{\gamma\delta}=-\frac12\left(\delta_{\alpha\delta}\delta_{\beta\gamma}-\frac13\delta_{\alpha\beta}\delta_{\gamma\delta}\right)",
        "refer/papers/平凡化映射威尔逊流与HMC_latex/chapters/backmatter.tex:22-41",
        "verified",
        "derive_su3_generator_identities",
        "用反厄米 Gell--Mann 生成元 T=i lambda/2 的基本表示逐项验证归一化、结构常数代数和完备性；不替代一般表示、路径积分或非阿贝尔动力学推导。",
    ),
    "su3_cayley_hamilton": FormulaSpec(
        "su3_cayley_hamilton",
        r"Q^3-c_1Q-c_0I=0,\quad c_0=\det Q=\frac13\mathrm{Tr}(Q^3),\quad c_1=\frac12\mathrm{Tr}(Q^2)\ge0,\quad 27c_0^2-4c_1^3\le0",
        "refer/papers/SU3链接变量解析涂抹_latex/chapters/section03.tex:1-18",
        "verified",
        "derive_su3_cayley_hamilton",
        "对一般无迹 3×3 矩阵逐元素验证 Cayley--Hamilton 与 c0 恒等式；对实对角特征值验证 c1 的平方和形式和判别式负平方形式，不替代一般 Hermitian 谱定理或涂抹数值实现。",
    ),
    "correlated_chi_square_profile": FormulaSpec(
        "correlated_chi_square_profile",
        r"\chi^2=(d-B\lambda)^T W(d-B\lambda)+\lambda^T\lambda,\quad A=I+B^TWB,\quad \widehat\lambda=A^{-1}B^TWd",
        "refer/papers/CT18_Global_Analysis_latex/chapters/section03.tex:23-80",
        "verified",
        "derive_correlated_chi_square_profile",
        "在两个数据点和一个相关 nuisance 参数的精确有限维模型中验证驻点、A 矩阵、Woodbury 协方差逆、profiled chi^2 及 shifted residual；采用 W=diag(s_i^{-2}) 的未归一化约定，不代入 CT18 数值数据。",
    ),
    "ising_mean_field": FormulaSpec(
        "ising_mean_field",
        r"M=Z_0^{-1}\sum_{s_0=\pm1}s_0e^{(2dKM+h)s_0}=\tanh(2dKM+h),\quad 2dK=1\ \text{at critical linear slope}",
        "refer/papers/夸克禁闭_latex/chapters/section06.tex:80-97",
        "verified",
        "derive_ising_mean_field",
        "在 s_0=±1 的有限和中验证配分函数、双曲正切自洽式和 M=h=0 的临界线性斜率；平均场模型仅作公式基准，不替代格点 QCD 相变分析。",
    ),
    "ape_projection_su2": FormulaSpec(
        "ape_projection_su2",
        r"X^{(n+1)}=(1-|f|)U^{(n)}+\frac{f}{6}\Sigma_{U^{(n)}},\quad U^{(n+1)}=X^{(n+1)}\left([X^{(n+1)}]^\dagger X^{(n+1)}\right)^{-1/2}",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section02.tex:13-20",
        "verified",
        "derive_ape_projection_su2",
        "用 U=I、六个相同 SU(2) staple 的显式代理验证 APE 线性组合、极化逆平方根、投影后的幺正性和行列式；同时展示 X=0 的奇异例，不把单例推广为一般模拟保证。",
    ),
    "wilson_eigenvalue_statistics": FormulaSpec(
        "wilson_eigenvalue_statistics",
        r"\mu_N=\langle\theta_N\rangle,\quad \sigma_N^2=\langle\theta_N^2\rangle-\langle\theta_N\rangle^2,\quad \theta_N=\frac{s}{\alpha}+\pi(1-g),\quad \alpha=\sqrt{\frac{0.8131947928}{\sigma_N^2}},\quad g=1-\frac{1}{\pi}\left[\mu_N+\frac{1.7710868074}{\alpha}\right]",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section03.tex:25-67",
        "verified",
        "derive_wilson_eigenvalue_statistics",
        "精确展开方差、偏度和超额峰度的中心矩，并验证源文普适均值/方差常数作为输入时仿射标度变量的逆变换、均值和方差标定；普适常数与 Painleve II 数值解不由 SymPy 重新计算。",
    ),
    "wilson_fourier_endpoint": FormulaSpec(
        "wilson_fourier_endpoint",
        r"\hat\rho(\theta)=\sum_{k=0}^{N}f_k\cos(k\theta),\quad \hat\rho(\pi)=\sum_{k=0}^{k_m}(-1)^k f_k,\quad k_m<N/2",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section03.tex:228-236",
        "verified",
        "derive_wilson_fourier_endpoint",
        "在有限整数 Fourier 模式上精确验证 pi 端点的交错和、2pi 周期性以及 N=44、k_m=21 的示例不等式；截断稳定性和实际系数仍需数值数据。",
    ),
    "wilson_edge_universal_formulas": FormulaSpec(
        "wilson_edge_universal_formulas",
        r"p(s)=\left[\int_s^\infty q^2(x)\,dx\right]\exp\left[-\int_s^\infty(x-s)q^2(x)\,dx\right],\quad q''=s q+2q^3,\quad p_f(s)=c\{\operatorname{Ai}'^2-s\operatorname{Ai}^2\}+d\{3s^2\operatorname{Ai}^2-2s\operatorname{Ai}'^2-3\operatorname{Ai}\operatorname{Ai}'\}",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section03.tex:42-59,82-89",
        "verified",
        "derive_wilson_edge_universal_formulas",
        "用积分的 Leibniz 规则验证极端本征值密度的导数结构，用 SymPy Airy 函数验证 Ai 方程与边缘核导数；Painleve II 解、拟合系数和数值普适常数作为源文输入，不由此数值求解。",
    ),
    "wilson_continuum_scale": FormulaSpec(
        "wilson_continuum_scale",
        r"\frac{1}{T_c(b)}=0.26\left[\frac{11}{48\pi^2b_I}\right]^{51/121}e^{24\pi^2b_I/11},\quad b_I=b e(b),\quad a=\frac{T_c}{t_c},\quad l t_c=L T_c,\quad f=0.25-(0.6128\,l t_c)^2",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section03.tex:129-146,169-177",
        "verified",
        "derive_wilson_continuum_scale",
        "验证两圈经验式的倒数关系、b_I 定义、格距与无量纲长度换算、O(T_c^2) 显式代表项的连续极限及穿越线代入；不重拟合源文数值数据。",
    ),
    "two_dimensional_wilson_loop": FormulaSpec(
        "two_dimensional_wilson_loop",
        r"\frac{1}{N}\langle\mathrm{Tr}\,W^n\rangle=\frac{1}{n}L_{n-1}^{(1)}(2An)e^{-An}",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section04.tex:76-83",
        "verified",
        "derive_two_dimensional_wilson_loop",
        "对 n=1,2,3 的广义 Laguerre 多项式展开验证二维大 N Wilson 圈公式、A=0 归一化和多项式乘指数结构；不展开二维 QCD 系综积分。",
    ),
    "instanton_holonomy_su2": FormulaSpec(
        "instanton_holonomy_su2",
        r"A_\mu=i\frac{x^2}{x^2+\rho^2}U^\dagger\partial_\mu U,\quad U=\frac{x_4+i\vec x\cdot\vec\sigma}{\sqrt{x^2}},\quad {\cal P}e^{i\oint A_\mu dx_\mu}=e^{i\pi(1-\rho/\sqrt{\rho^2+4R^2})\sigma_3}",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section04.tex:41-53",
        "verified",
        "derive_instanton_holonomy_su2",
        "在显式 SU(2) 局部坐标图上验证 U 的幺正/行列式、A_4 的 Hermitian/无迹结构以及源文 holonomy 的 SU(2) 性质和 rho 极限；不重算路径序积分。",
    ),
    "grassmann_determinant_identity": FormulaSpec(
        "grassmann_determinant_identity",
        r"\int\prod_i^n(d\bar\psi_i d\psi_i)e^{z\sum_i\bar\psi_i\psi_i-\sum_i\bar\psi_iU_i\psi_{i+1}}=\det(z^n+W),\quad \psi_{n+1}=-\psi_1",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section04.tex:121-135",
        "verified",
        "derive_grassmann_determinant_identity",
        "对 N=2、n=2 对角颜色块矩阵和标量 n=3 构造二次型系数矩阵，验证周期反号边界与 det(z^n I+U_1...U_n)；不执行 Grassmann 积分或大 N 鞍点。",
    ),
    "wilson_gap_scaling": FormulaSpec(
        "wilson_gap_scaling",
        r"g(f,L,b)=A(L,b)\sqrt{f-F_c(L,b)},\quad g^2(l t_c)=A\ln\frac{l}{l_c}",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section03.tex:103-111,192-197",
        "verified",
        "derive_wilson_gap_scaling",
        "在正的拟合增量上验证平方根闭隙极限和临界点处对数式归零，并检查 l/l_c 无量纲；振幅与临界长度仍是源文数值外推参数。",
    ),
    "wilson_smearing_kernel": FormulaSpec(
        "wilson_smearing_kernel",
        r"h_{\mu\nu}(q)=f(q)P^T_{\mu\nu}+P^L_{\mu\nu},\quad f(q)=1-\frac{f}{6}\widetilde q^2,\quad \widetilde q_\mu=2\sin\frac{q_\mu}{2},\quad \lim_{n\to\infty}(1-c/n)^n=e^{-c},\quad 0<f<\frac34",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section02.tex:73-96",
        "verified",
        "derive_wilson_smearing_kernel",
        r"在线性化 APE/Wilson 涂抹核中验证横纵向投影代数、迭代幂和弱涂抹指数极限；二维 \widetilde q^2≤8 给出一步因子为正时的 f<3/4。非线性 SU(N) 投影和大 N 数值相变不由此推出。",
    ),
    "wilson_smearing_scaling": FormulaSpec(
        "wilson_smearing_scaling",
        r"b=\frac{\beta}{2N^2}=\frac{1}{g_{\rm YM}^2N},\quad a(b)=\frac{T_c(b)}{t_c},\quad l_\alpha=L_\alpha a(b),\quad n=\frac{(L_1+L_2)^2}{4},\quad f=\frac{\tilde f}{1+M^2L^2},\quad M=ma(b)",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section02.tex:4-5,33-40,58-61,94-97",
        "verified",
        "derive_wilson_smearing_scaling",
        r"验证裸 't Hooft 耦合、格距/物理长度换算、方圈 n=L^2、物理涂抹尺度 a^2fn，以及 M=m a 后的 M L=m l 和 f 截断剖面；不把临界线或数值端点当作代数结论。",
    ),
    "lattice_dispersion_relations": FormulaSpec(
        "lattice_dispersion_relations",
        r"\hat p_\mu=\frac{2}{a}\sin\frac{ap_\mu}{2},\quad \bar p_\mu=\frac{1}{a}\sin(ap_\mu),\quad \cosh(aE_\pi)=\cosh(am_\pi)+\frac{a^2}{2}\hat{\mathbf p}^2",
        "refer/papers/高动量强子新夸克涂抹_latex/chapters/section04.tex:34-57",
        "verified",
        "derive_lattice_dispersion_relations",
        "用正实一维动量分量验证 hat/bar 动量的 a→0 极限、离散平方的周期性，以及 pion/Wilson 自由色散在 p=0 的静止质量极限；不验证论文的强子拟合数据。",
    ),
    "boosted_smearing_width": FormulaSpec(
        "boosted_smearing_width",
        r"\nabla^2\to\gamma^{-2}\nabla_\parallel^2+\nabla_\perp^2,\quad N=1+2\omega'(d-1+\gamma^{-2}),\quad \omega'=\frac{\omega}{1+2\omega(1-\gamma^{-2})}",
        "refer/papers/高动量强子新夸克涂抹_latex/chapters/backmatter.tex:41-101",
        "verified",
        "derive_boosted_smearing_width",
        "在 d=3、晶轴方向和正参数有限维模型中验证 boost Laplacian 改写、链方向归一化、gamma=1 退化、横向方差匹配与平行宽度 1/gamma 缩减；不验证强子拟合。",
    ),
    "momentum_smearing_shift": FormulaSpec(
        "momentum_smearing_shift",
        r"\widetilde f(p)\mapsto\widetilde f(p-k),\quad f_z\mapsto e^{ikz}f_z",
        "refer/papers/Novel_Quark_Smearing_High_Momenta_latex/chapters/section02.tex:21-56",
        "verified",
        "derive_momentum_smearing_shift",
        "用连续 Gaussian 核验证相位调制与 Fourier 平移，并显式区分正负号 Fourier 约定。",
    ),
    "gradient_flow": FormulaSpec(
        "gradient_flow",
        r"\partial_tB_\mu=D_\nu G_{\nu\mu},\quad t\sim L_{\rm sm}^2",
        f"{_REPORT}:67-74,251-253",
        "verified",
        "derive_gradient_flow",
        "在自由/阿贝尔横向规范下验证热方程、Fourier 衰减、高斯核和二阶矩。",
    ),
    "wilson_flow_five_dimensional": FormulaSpec(
        "wilson_flow_five_dimensional",
        r"\partial_\tau A_\nu=D_\mu F_{\mu\nu},\quad F_{5\nu}=D_\mu F_{\mu\nu},\quad [\tau]=L^2",
        "refer/papers/连续威尔逊圈的无穷N相变_latex/chapters/section04.tex:8-20",
        "verified",
        "derive_wilson_flow_five_dimensional",
        "在二维 Abelian Fourier 模式中验证场强反对称性、D_mu F_{mu nu} 的横向算子、第五维关系、二次作用量单调形式与量纲平衡；不替代完整非阿贝尔拓扑五维理论或 Parisi--Wu 系综推导。",
    ),
    "wilson_flow_runge_kutta": FormulaSpec(
        "wilson_flow_runge_kutta",
        r"W_1=e^{Z_0/4}W_0,\quad W_2=e^{8Z_1/9-17Z_0/36}W_1,\quad V_{t+\epsilon}=e^{3Z_2/4-8Z_1/9+17Z_0/36}W_2,\quad Z_i=\epsilon Z(W_i)",
        "refer/papers/威尔逊流的性质与应用_latex/chapters/backmatter.tex:97-126",
        "verified",
        "derive_wilson_flow_runge_kutta",
        "在可交换正标量群代理 Z(V)=V 上逐项验证源文三阶显式 Runge--Kutta 更新的 epsilon^0--epsilon^3 系数和 epsilon^4 首个局部误差；非交换 BCH 项及实际格点积分稳定性未展开。",
    ),
    "gradient_flow_duhamel_solution": FormulaSpec(
        "gradient_flow_duhamel_solution",
        r"\widetilde B(t,p)=\widetilde K_t(p)\widetilde A(p)+\int_0^t ds\,\widetilde K_{t-s}(p)\widetilde R(s,p)",
        "refer/papers/梯度流的微扰分析_latex/chapters/section02.tex:68-91",
        "verified",
        "derive_gradient_flow_duhamel_solution",
        "对单一 Fourier 模式 K_t=exp(-lambda t)、指数源 R(s)=R exp(-kappa s) 精确积分，验证 Duhamel 解的流方程、初值和 lambda=kappa 连续极限；非阿贝尔流顶点未展开。",
    ),
    "wilson_flow_reference_scale": FormulaSpec(
        "wilson_flow_reference_scale",
        r"\left.\{t^2\langle E\rangle\}\right|_{t=t_0}=0.3,\quad \frac{\sqrt{8t_0}}{r_0}\ \text{有良好连续极限}",
        "refer/papers/威尔逊流的性质与应用_latex/chapters/section03.tex:112-119",
        "verified",
        "derive_wilson_flow_reference_scale",
        "用 t^2<E(t)>=c_0+c_1 t/r_0^2 的显式代表模型解出 t_0/r_0^2，验证平滑半径比及代表性 a^2 截止项的连续极限；不重现源文系综数据。",
    ),
    "wilson_lattice_flow_monotonicity": FormulaSpec(
        "wilson_lattice_flow_monotonicity",
        r"S_W(U)=\frac{1}{g_0^2}\sum_p\operatorname{ReTr}(1-U(p)),\quad \dot V_t=-g_0^2\{\partial S_W(V_t)\}V_t,\quad \frac{dS_W}{dt}\le0",
        "refer/papers/威尔逊流的性质与应用_latex/chapters/section01.tex:21-37",
        "verified",
        "derive_wilson_lattice_flow_monotonicity",
        "在 U(1) 单方格代理中用反厄米 Lie 导数验证群值流方程、幺正性、作用量单调下降与小角展开；不替代一般 SU(N) 多链接证明。",
    ),
    "gauge_flow_kernel": FormulaSpec(
        "gauge_flow_kernel",
        r"K_t(p)_{\mu\nu}=P^T_{\mu\nu}e^{-tp^2}+P^L_{\mu\nu}e^{-\alpha_0tp^2}",
        "refer/papers/梯度流的微扰分析_latex/chapters/section02.tex:44-72",
        "verified",
        "derive_gauge_flow_kernel",
        "在二维非零动量的显式投影矩阵上验证式 2.8 的初值、投影代数、半群和线性流方程；非阿贝尔流顶点仍为未解析结构。",
    ),
    "flowed_propagators": FormulaSpec(
        "flowed_propagators",
        r"D_{\mu\nu}(p;t,s)=\frac{P^T_{\mu\nu}e^{-(t+s)p^2}+\xi P^L_{\mu\nu}e^{-\kappa(t+s)p^2}}{p^2},\quad S(p;t,s)=\frac{-i\slashed p+m}{p^2+m^2}e^{-(t+s)p^2}",
        "refer/papers/梯度流高阶计算的技术与结果_latex/chapters/backmatter.tex:27-58",
        "verified",
        "derive_flowed_propagators",
        "在二维 Euclidean p=(1,2) 的有限维模型中验证横纵向投影完备性、Feynman 规范初值、流时间热核方程、夸克 Dirac 逆关系和鬼传播子形式；颜色指标、非阿贝尔顶点与圈积分未展开。",
    ),
    "gradient_flow_energy_density": FormulaSpec(
        "gradient_flow_energy_density",
        r"K_t(z)=\frac{e^{-z^2/(4t)}}{(4\pi t)^{D/2}},\quad \langle E\rangle_{D=4}=\frac{3(N^2-1)g^2}{128\pi^2t^2}",
        "refer/papers/威尔逊流的性质与应用_latex/chapters/section02.tex:80-95,160-185,236-279",
        "verified",
        "derive_gradient_flow_energy_density",
        "验证四维高斯核归一化、均方半径 8t、D=4 领头能量密度和 alpha=g^2/(4pi) 换写；一圈系数仅保留为形式符号。",
    ),
    "heat_kernel_semigroup": FormulaSpec(
        "heat_kernel_semigroup",
        r"K_{t_1}*K_{t_2}=K_{t_1+t_2},\quad e^{-p^2t_1}e^{-p^2t_2}=e^{-p^2(t_1+t_2)}",
        "refer/papers/威尔逊流的性质与应用_latex/chapters/section02.tex:80-95",
        "verified",
        "derive_heat_kernel_semigroup",
        "用一维高斯卷积和 Fourier 模式验证梯度流时间的半群复合；边界取整个实轴。",
    ),
    "gradient_flow_pole_cancellation": FormulaSpec(
        "gradient_flow_pole_cancellation",
        r"b_0=\frac{1}{16\pi^2}(\frac{11}{3}N-\frac{2}{3}N_f),\quad c_1^{\rm pole}=\frac{b_0}{\epsilon}",
        "refer/papers/威尔逊流的性质与应用_latex/chapters/section02.tex:223-259",
        "verified",
        "derive_gradient_flow_pole_cancellation",
        "按 g^4 截断验证能量密度一圈极点与裸耦合重写项抵消；有限项和完整维数正规化积分保留为转录结构。",
    ),
    "target_mass_corrections": FormulaSpec(
        "target_mass_corrections",
        r"\mathcal Q^\parallel=q+\frac14\frac{m^2v^2}{(pv)^2}(xq'+q),\quad \mathcal P=q+\frac14z^2v^2m^2x^2\int_{|x|}^1\frac{dy}{y}q(x/y)",
        "refer/papers/大动量有效理论再论_latex/chapters/section02.tex:153-208",
        "verified",
        "derive_target_mass_corrections",
        "在 0<x<1 的显式 q(x)=x^2 与端点形状 q(x)=(1-x)^3 上验证导数项、卷积积分以及 qPDF 端点增强/pPDF 端点压低。",
    ),
    "qpdf_ppdf_fourier_inversion": FormulaSpec(
        "qpdf_ppdf_fourier_inversion",
        r"Q(x)=|pv|\int\frac{dz}{2\pi}e^{-ixz(pv)}I(zpv),\quad P(x,z)=|z|\int\frac{d(pv)}{2\pi}e^{-ixz(pv)}I(zpv)",
        "refer/papers/大动量有效理论再论_latex/chapters/section02.tex:35-85",
        "verified",
        "derive_qpdf_ppdf_fourier_inversion",
        "用实轴归一化高斯 PDF 精确验证 qPDF 与 pPDF Fourier 反演及 1/(2pi) 归一化；不处理有限支撑端点。",
    ),
    "flow_mcmc_balance": FormulaSpec(
        "flow_mcmc_balance",
        r"A(\phi,\phi')=\min\{1,\frac{\widetilde p(\phi)}{p(\phi)}\frac{p(\phi')}{\widetilde p(\phi')}\},\quad pT=p",
        "refer/papers/基于流的格点MCMC生成模型_latex/chapters/section02.tex:24-80,134-153",
        "verified",
        "derive_flow_mcmc_balance",
        "在两状态精确模型中验证独立 Metropolis detailed balance、平稳分布和 KL 损失恒等式；不测量实际流模型性能。",
    ),
    "phi4_lattice_observables": FormulaSpec(
        "phi4_lattice_observables",
        r"S(\phi)=\sum_x[\phi\Box\phi+m^2\phi^2+\lambda\phi^4],\quad m_p^{\rm eff}=\operatorname{arccosh}\frac{G(t-1)+G(t+1)}{2G(t)}",
        "refer/papers/基于流的格点MCMC生成模型_latex/chapters/section03.tex:8-22,50-80,152",
        "verified",
        "derive_phi4_lattice_observables",
        "在四点一维周期格点上验证离散 Laplacian、作用量梯度、Z2 偶对称、连通二点/磁化率和周期两态有效质量；不替代论文的数值系综。",
    ),
    "mcmc_autocorrelation": FormulaSpec(
        "mcmc_autocorrelation",
        r"\rho(\tau)/\rho(0)=\mathbb E[p_{\rm rej}^{\tau}]\ge(1-a)^\tau,\quad \tau_{\mathcal O}^{\rm int}=\frac12+\sum_{\tau\ge1}\rho(\tau)/\rho(0)",
        "refer/papers/基于流的格点MCMC生成模型_latex/chapters/section02.tex:175-236",
        "verified",
        "derive_mcmc_autocorrelation",
        "用两状态拒绝概率验证 Jensen 下界，并对几何相关模型求出积分自相关时间；不包含有限样本 bootstrap 误差。",
    ),
    "pseudo_pdf_one_loop": FormulaSpec(
        "pseudo_pdf_one_loop",
        r"B(w)=\left[\frac{1+w^2}{1-w}\right]_+,\quad \mathcal I=\mathfrak M+\frac{\alpha_s C_F}{2\pi}\,B\otimes\mathfrak M",
        "refer/papers/伪部分子分布的单圈演化_latex/chapters/section03.tex:80-141",
        "verified",
        "derive_pseudo_pdf_one_loop",
        "按 plus 分布测试函数作用实现端点抵消，验证 MNL 与 MNL2 核的代数重写以及有效尺度；不替代完整单圈图形计算。",
    ),
    "pseudo_pdf_ir_regulators": FormulaSpec(
        "pseudo_pdf_ir_regulators",
        r"I_K(z_3^2)=\int_0^\infty\frac{d\alpha}{\alpha}e^{-z_3^2/(4\alpha)-\alpha m^2}=2K_0(mz_3),\quad I_G=\Gamma(0,z_3^2/z_0^2)",
        "refer/papers/伪部分子分布的单圈演化_latex/chapters/section03.tex:20-64",
        "verified",
        "derive_pseudo_pdf_ir_regulators",
        "验证 Schwinger/截断变量代换和小距对数常数；Bessel 积分使用标准特殊函数积分表示，未把 SymPy 的 Meijer-G 输出强行改写为自动证明。",
    ),
    "renormalization": FormulaSpec(
        "renormalization",
        r"O^R(z,\mu)=Z(z,\mu,a)O^{\rm bare}(z,a)",
        f"{_REPORT}:67-74,905-907",
        "verified",
        "derive_renormalization",
        "验证乘法逆关系、重正化因子复合律及一个可因子化截止项的抵消。",
    ),
    "lamet_matching": FormulaSpec(
        "lamet_matching",
        r"\widetilde q=\int dy\,Cq+\mathcal O(\Lambda_{\rm QCD}^2/P_z^2)",
        f"{_REPORT}:67-74,730-732",
        "verified",
        "derive_lamet_matching",
        "验证幂修正的无量纲缩放与 P_z→∞ 极限；不伪造论文特定匹配核。",
    ),
    "lamet_lightcone_kinematics": FormulaSpec(
        "lamet_lightcone_kinematics",
        r"q^2=-Q^2,\quad P^2=M^2,\quad x_B=\frac{Q^2}{2P\cdot q},\quad k=(k\cdot n)p+(k\cdot p)n+k_\perp",
        "refer/papers/大动量有效理论综述_latex/chapters/section01.tex:60-110",
        "verified",
        "derive_lamet_lightcone_kinematics",
        "在 Minkowski 度规下精确验证 DIS 壳条件、Bjorken 关系、轻锥分解和 P^z→∞ 时的平方幂修正；不计算 PDF 矩阵元。",
    ),
    "gpd_kinematics_and_matching": FormulaSpec(
        "gpd_kinematics_and_matching",
        r"\Delta_\perp^2=-t-4\xi^2(M^2-t/4),\quad \xi_{\max}^2=\frac{-t}{-t+4M^2},\quad C=|y/\xi|\,\bar C",
        "refer/papers/大动量有效理论综述_latex/chapters/section04.tex:47-112",
        "verified",
        "derive_gpd_kinematics_and_matching",
        "由同质量非前向外部态的壳条件推出光锥与准 GPD 横向动量边界，并在正 xi、y 分支验证匹配测度重写；不计算自旋器和一圈核。",
    ),
    "pion_da_normalization": FormulaSpec(
        "pion_da_normalization",
        r"\phi_\pi^{\rm as}(x)=6x(1-x),\quad \int_0^1dx\,\phi_\pi(x)=1",
        "refer/papers/大动量有效理论综述_latex/chapters/section04.tex:145-177",
        "verified",
        "derive_pion_da_normalization",
        "验证渐近 pion DA 的归一化、x↔1-x 对称性、中心矩和坐标空间 Fourier 相位；不计算介子矩阵元或方案匹配核。",
    ),
    "tmd_soft_rge_consistency": FormulaSpec(
        "tmd_soft_rge_consistency",
        r"\ln S=\ln\frac{\mu^2}{2\delta^+\delta^-}K+\mathcal D_2,\quad \mu^2\frac{dK}{d\mu^2}=-\Gamma_{\rm cusp},\quad 2\zeta\frac{d\ln f}{d\zeta}=K",
        "refer/papers/大动量有效理论综述_latex/chapters/section05.tex:98-178",
        "verified",
        "derive_tmd_soft_rge_consistency",
        "在固定尖点核/软异常维数的无量纲对数代理中验证软因子 RGE、D2 递推、Collins–Soper 解和初值；不重算 running coupling 与圈积分常数。",
    ),
    "pseudo_itd": FormulaSpec(
        "pseudo_itd",
        r"{\cal M}(-pz,-z^2)=\int_{-1}^{1}dx\,e^{-ix(pz)}{\cal P}(x,-z^2),\quad {\mathfrak M}=\frac{{\cal M}(\nu,z_3^2)}{{\cal M}(0,z_3^2)}",
        "refer/papers/伪部分子分布的单圈演化_latex/chapters/section02.tex:3-60",
        "verified",
        "derive_pseudo_itd",
        "在支撑[-1,1]的归一化常数 PDF 上验证 Fourier 符号、矩导数、乘法 UV 因子抵消和短距尺度；OPE 匹配核保留形式积分。",
    ),
    "pdf_moment_relations": FormulaSpec(
        "pdf_moment_relations",
        r"a_0^{(n)}=\int_0^1d\xi\,\xi^{n-1}[f(\xi)+(-1)^n\bar f(\xi)]=\int_{-1}^1d\xi\,\xi^{n-1}f(\xi),\quad K_n(r)=\sum_j{n-j\choose j}r^j",
        "refer/papers/Quasi_PDF_Gradient_Flow_latex/chapters/section02.tex:67-88; chapters/section03.tex:133-183",
        "verified",
        "derive_pdf_moment_relations",
        "用可积多项式 PDF 验证负 xi 延拓和 Mellin 矩恒等式，并验证靶质量多项式 K_n；不计算局域 twist-two 矩阵元。",
    ),
    "langevin_fokker_planck": FormulaSpec(
        "langevin_fokker_planck",
        r"\partial_\tau\phi=-\frac{\delta S_E}{\delta\phi}+\eta,\quad P_{\rm eq}[\phi]\propto e^{-S_E[\phi]/\alpha}",
        "refer/papers/扩散模型即随机量化_latex/chapters/section02.tex:4-83",
        "verified",
        "derive_langevin_fokker_planck",
        "在一维谐作用量上验证漂移、Fokker--Planck 定态高斯、方差和 LQ=0；泛函指标与收敛谱仍是结构层。",
    ),
    "diffusion_processes": FormulaSpec(
        "diffusion_processes",
        r"\frac{d\phi}{d\xi}=f+g\eta,\quad p_\xi(\phi_\xi|\phi_0)=\mathcal N,\quad \frac{d\log p}{dt}=-\nabla\cdot\tilde f",
        "refer/papers/扩散模型即随机量化_latex/chapters/section03.tex:24-141",
        "verified",
        "derive_diffusion_processes",
        "在有限维 Gaussian/线性流假设下验证方差扩张核、反向时间变换、条件分数到边缘分数的投影、概率流连续性方程和 Jacobian 散度关系；神经网络逼近误差与泛函 QFT 采样不由此推出。",
    ),
    "trivializing_map": FormulaSpec(
        "trivializing_map",
        r"dU= dV\,\det T'(V),\quad S(T(V))-\ln\det T'(V)=\mathrm{const}",
        "refer/papers/平凡化映射威尔逊流与HMC_latex/chapters/section02.tex:65-103",
        "verified",
        "derive_trivializing_map",
        "用一维非线性映射和可积线性流验证测度 Jacobian、Jacobian 演化及构造的平凡化 pullback 作用量；不声称任意 QCD 作用量均已平凡化。",
    ),
    "trivializing_flow_factorization": FormulaSpec(
        "trivializing_flow_factorization",
        r"\ln\det\trans_{t,*}=tS(U_t)+C_t,\quad S(U_t)-\ln\det\trans_{t,*}=(1-t)S(U_t)-C_t",
        "refer/papers/平凡化映射威尔逊流与HMC_latex/chapters/section04.tex:1-25",
        "verified",
        "derive_trivializing_flow_factorization",
        "将源文流 Jacobian 条件作为标量代理，精确验证作用量--Jacobian 因子化和 t=1 时场无关；不求解非阿贝尔流方程。",
    ),
    "euler_map_inverse_and_jacobian": FormulaSpec(
        "euler_map_inverse_and_jacobian",
        r"U'=e^{\epsilon Z(U)}U,\quad X_{n+1}=Z(e^{-\epsilon X_n}U'),\quad |\epsilon|<1/8,\quad \det T=\prod\det E_{*}",
        "refer/papers/平凡化映射威尔逊流与HMC_latex/chapters/section05.tex:1-80,121-151",
        "verified",
        "derive_euler_map_inverse_and_jacobian",
        "在 U(1) 局部角坐标 Z(x)=sin(x) 中验证固定点方程、压缩界和复合 Jacobian；源文 SU(3) 的 |epsilon|<1/8 矩阵充分条件仅作来源记录，未由标量代理重证。",
    ),
    "hmc_scalar": FormulaSpec(
        "hmc_scalar",
        r"\widehat H=\frac12(\widehat p,\widehat p)+S(T(V))-\ln\det T'(V),\quad K=T'^TT'",
        "refer/papers/平凡化映射威尔逊流与HMC_latex/chapters/section02.tex:113-150",
        "verified",
        "derive_hmc_scalar",
        "在一维线性场变换与谐作用量上验证正则动量变换、Hamilton 方程和连续能量守恒；不验证离散 leapfrog 接受率。",
    ),
    "flow_integral_ibp": FormulaSpec(
        "flow_integral_ibp",
        r"I(t,\mathbf n,\mathbf a,\mathbf c,D),\quad \mathcal D_{ij}=\partial_{p_i}\!\cdot p_j,\quad \int_0^{t_r^{\rm up}}dt_r\,\partial_{t_r}f=f(t_r^{\rm up})-f(0)",
        "refer/papers/梯度流高阶计算的技术与结果_latex/chapters/section03.tex:74-125",
        "verified",
        "derive_flow_integral_ibp",
        "用径向高斯传播子原型验证全导数 IBP、(D-2n)I_n-2tI_{n-1}=0、t 尺度律及流时间边界项；不替代 P37 的多圈主积分约化。",
    ),
    "gradient_flow_rg_log_recursion": FormulaSpec(
        "gradient_flow_rg_log_recursion",
        r"k e_{n,k}=\sum_{l=0}^{n-1}(n-l)e_{n-l-1,k-1}\beta_l,\quad L(z)=\ln(2z)+\gamma_E",
        "refer/papers/梯度流高阶计算的技术与结果_latex/chapters/section04.tex:184-251",
        "verified",
        "derive_gradient_flow_rg_log_recursion",
        "由 D x=-x^2(beta_0+beta_1 x+...) 和 D L=1 构造 e_1/e_2，精确检查三个低阶递推实例与 RGE 残差；不重算圈积分常数。",
    ),
    "gradient_flow_scheme_conversion": FormulaSpec(
        "gradient_flow_scheme_conversion",
        r"\alpha_{\rm gf}=\alpha_s[1+e_1x+e_2x^2+\cdots],\quad \alpha_s=\alpha_{\rm gf}[1-e_1y+(2e_1^2-e_2)y^2+\cdots],\quad \beta_{{\rm gf},2}=\beta_2-e_1\beta_1+(e_2-e_1^2)\beta_0",
        "refer/papers/梯度流高阶计算的技术与结果_latex/chapters/section05.tex:1-51",
        "verified",
        "derive_gradient_flow_scheme_conversion",
        "用形式幂级数链式法则验证耦合反演及三阶 beta 系数变换，确认前两个 beta 系数不变；不代入论文数值 e_i。",
    ),
    "emt_operator_basis": FormulaSpec(
        "emt_operator_basis",
        r"\widetilde{\mathcal O}_{i}=\zeta_{ij}\mathcal O_j,\quad c_2=\widetilde c_2+c_1/4,\quad c_4=\widetilde c_4+2c_3",
        "refer/papers/含费米子场的格点能动量张量_latex/chapters/section04.tex:120-182",
        "verified",
        "derive_emt_operator_basis",
        "对任意 5×5 逆匹配矩阵验证源文能动量张量系数的基底重组，并检查 D=4 规范无迹组合；不计算 zeta 矩阵的微扰值。",
    ),
    "ringed_fermion_normalization": FormulaSpec(
        "ringed_fermion_normalization",
        r"\mathring\chi=\sqrt{\frac{-2\dim(R)N_f}{(4\pi)^2t^2\langle\bar\chi\overleftrightarrow{\not D}\chi\rangle}}\,\chi,\quad \langle R(t)\rangle=\frac{-2\dim(R)N_f}{(4\pi)^2t^2}(8\pi t)^\epsilon",
        "refer/papers/含费米子场的格点能动量张量_latex/chapters/section03.tex:229-261",
        "verified",
        "derive_ringed_fermion_normalization",
        "代入树级动能算符期望值验证归一化平方和 D=4 极限，并做质量维数补偿检查；忽略质量和高阶圈修正。",
    ),
    "emt_trace_anomaly": FormulaSpec(
        "emt_trace_anomaly",
        r"T^\mu_{\ \mu}=-\frac{\beta(g)}{2g^3}\{F^2\}_R-(1+\gamma_m)m\{\bar\psi\psi\}_R",
        "refer/papers/含费米子场的格点能动量张量_latex/chapters/section02.tex:99-139",
        "verified",
        "derive_emt_trace_anomaly",
        "代入 beta=-b_0g^3-b_1g^5 与 gamma_m=d_0g^2+d_1g^4 验证规范项/质量项符号和阶数；不计算重正化算符矩阵元。",
    ),
    "collins_soper_evolution": FormulaSpec(
        "collins_soper_evolution",
        r"2\zeta\,d\ln f^{\rm TMD}/d\zeta=K(b_\perp,\mu),\quad \mu^2dK/d\mu^2=-\Gamma_{\rm cusp}",
        "refer/papers/从准TMD波函数确定CS核_latex/chapters/section02.tex:16-28",
        "verified",
        "derive_collins_soper_evolution",
        "验证固定尖点核的解析解；running alpha_s 的论文特定积分和高阶系数不在此展开。",
    ),
    "euclidean_to_tmd": FormulaSpec(
        "euclidean_to_tmd",
        r"\mathcal O_{\rm Euclid}\xrightarrow{\rm matching/evolution}F_{\rm TMD}",
        f"{_REPORT}:67-74,1650-1652",
        "structural",
        "derive_tmd_fourier",
        "用归一化二维高斯例子验证 Fourier 结构；软因子、CS 核和方案转换不在此自动推出。",
    ),
    "normalizing_flow": FormulaSpec(
        "normalizing_flow",
        r"z\sim p(z),\quad U=f_\theta(z),\quad p_\theta(U)\ {与目标系统比较}",
        f"{_REPORT}:2015-2017",
        "verified",
        "derive_normalizing_flow",
        "验证二维仿射 coupling layer 的 Jacobian、对数行列式和密度变换；不等同于规范等变性证明。",
    ),
    "wilson_area_law": FormulaSpec(
        "wilson_area_law",
        r"\langle W(C)\rangle\sim\exp[-\sigma A(C)]",
        f"{_REPORT}:114-116",
        "verified",
        "derive_wilson_area_law",
        "由矩形面积律和 T→∞ 定义推出 V(R)=σR，忽略周长项。",
    ),
    "mellin_convolution": FormulaSpec(
        "mellin_convolution",
        r"M_n[C\otimes q]=\int dy\,M_n[C(\cdot,y)]q(y)",
        "refer/papers/任意阶部分子分布矩_latex/chapters/section02.tex:4-8",
        "verified",
        "derive_mellin_convolution",
        "用显式多项式例子检查 Fubini 换序；一般式需要可积性假设。",
    ),
    "tmd_fourier": FormulaSpec(
        "tmd_fourier",
        r"F(x,b_T)=\int d^2k_T\,e^{ib_T\cdot k_T}f(x,k_T)",
        "refer/papers/LaMET计算TMD软函数_latex/chapters/section02.tex:16-21",
        "verified",
        "derive_tmd_fourier",
        "二维径向高斯示例的归一化和 Bessel Fourier 变换已由 SymPy 检查。",
    ),
    "quasi_pdf_tmd_relation": FormulaSpec(
        "quasi_pdf_tmd_relation",
        r"Q(y,P)/P=\int_{-\infty}^{\infty}dk_1\int_{-1}^{1}dx\,\mathcal F(x,k_1^2+(y-x)^2P^2)",
        "refer/papers/准分布动量分布与伪分布_latex/chapters/section03.tex:3-62",
        "verified",
        "derive_quasi_pdf_tmd_relation",
        "在归一化 Gaussian TMD 与平坦 x 支撑模型中验证横向积分、误差函数闭式、总归一化和远离端点的 P→∞ 点态极限；不替代一般 QCD 因子化证明。",
    ),
    "correlator_spectrum": FormulaSpec(
        "correlator_spectrum",
        r"C(t)=\sum_n A_n e^{-E_nt},\quad E_{\rm eff}(t)\to E_0",
        "refer/books/INTRODUCTION_TO_LATTICE_QCD_latex/chapters/sec17_correlators.tex:94-102",
        "verified",
        "derive_correlator_spectrum",
        "用两态模型验证连续和离散有效能量的大欧氏时间极限。",
    ),
}
